

services:
  postgres:
    image: postgres:15
    container_name: job_board_postgres
    environment:
      POSTGRES_DB: job_board_db
      POSTGRES_USER: job_board_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
